export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_FAILURE = 'WEATHER_FAILURE';
export const API_ACTION_TYPE = '__API_CALL__';